version: 2.1

orbs:
  codecov: codecov/codecov@1.0.4

defaults: &defaults
  working_directory: /src
  docker:
    - image: golang:1.12

jobs:
  get_source:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-{{ checksum "go.sum" }}
      - run:
          name: Populate Go Mod Cache
          command: |
            if [ ! -d /go/pkg/mod ]; then
              go mod download
            fi
      - save_cache:
          key: go-mod-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod
      - persist_to_workspace:
          root: /
          paths:
            - go/pkg/mod
            - src

  build_source:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /
      - run:
          name: Build Source
          command: go build ./...

  check_formatting:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /
      - run:
          name: Check Formatting
          command: test -z $(go fmt ./...)

  vet_source:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /
      - run:
          name: Vet Source
          command: go vet -all ./...

  lint_source:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /
      - run:
          name: Install golangci-lint
          command: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.15.0
      - run:
          name: Check for Lint
          command: golangci-lint run ./...

  lint_markdown:
    docker:
      - image: circleci/ruby:2.4.1-node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install markdownlint
          command: sudo npm install -g markdownlint-cli
      - run:
          name: Check for Lint
          command: markdownlint --config src/.markdownlint.json src/

  unit_test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /
      - run:
          name: Run Tests
          command: go test -coverprofile cover.out -race -timeout 60s ./...
      - codecov/upload:
          file: cover.out

workflows:
  version: 2

  build_and_test:
    jobs:
      - get_source
      - build_source:
          requires:
            - get_source
      - check_formatting:
          requires:
            - get_source
      - vet_source:
          requires:
            - get_source
      - lint_source:
          requires:
            - get_source
      - lint_markdown:
          requires:
            - get_source
      - unit_test:
          requires:
            - get_source
